# Generated by Django 3.2.5 on 2021-07-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='adresse',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='logo_site_footer',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='website',
            name='mapp',
            field=models.TextField(),
        ),
    ]
