# Generated by Django 3.2.5 on 2021-07-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('nom', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Agence',
                'verbose_name_plural': 'Agences',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('nom', models.CharField(max_length=255)),
                ('desc_categorie', models.FileField(upload_to='images')),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Nmb_annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('semaine', models.IntegerField(max_length=255)),
                ('mois', models.IntegerField(max_length=255)),
                ('annee', models.IntegerField(max_length=255)),
            ],
            options={
                'verbose_name': 'Nmb_annonce',
                'verbose_name_plural': 'Nmb_annonces',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.FileField(upload_to='images')),
                ('image', models.FileField(upload_to='images')),
                ('prix', models.FloatField(default=0)),
                ('periode', models.CharField(max_length=255)),
                ('detail', models.CharField(max_length=255)),
                ('lit', models.CharField(max_length=255)),
                ('sale_de_bain', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
