# Generated by Django 3.2.5 on 2021-07-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nmb_annonce',
            name='annee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nmb_annonce',
            name='mois',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nmb_annonce',
            name='semaine',
            field=models.IntegerField(default=0),
        ),
    ]
