# Generated by Django 3.2.5 on 2021-07-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210705_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='desc_categorie',
            field=models.TextField(),
        ),
    ]
