# Generated by Django 3.2.5 on 2021-07-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20210705_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('nom', models.IntegerField(default=0)),
                ('prenom', models.IntegerField(default=0)),
                ('email', models.IntegerField(default=0)),
                ('choix', models.CharField(choices=[('A', 'Appartements'), ('C', 'Car'), ('S', 'Shopping'), ('F', 'Food & Life'), ('T', 'Traveling')], max_length=50)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
