# Generated by Django 3.2.5 on 2021-07-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='icon',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
